CREATE TABLE IF NOT EXIST rarity (
    id INTEGER PRIMARY KEY,
    rarity TEXT NOT NULL,
    weight FLOAT NOT NULL
);

CREATE TABLE IF NOT EXIST item (
    id INTEGER PRIMARY KEY UNSIGNED NOT NULL AUTO_INCREMENT,
);

CREATE TABLE IF NOT EXIST itemClass (
    id INTEGER PRIMARY KEY UNSIGNED NOT NULL AUTO_INCREMENT,
    itemType TEXT NOT NULL
);

CREATE TABLE IF NOT EXIST weapon (
    id INTEGER PRIMARY KEY UNSIGNED NOT NULL AUTO_INCREMENT,
    name TEXT NOT NULL,
    damage INTEGER NOT NULL,
    speed INTEGER NOT NULL
);

CREATE TABLE IF NOT EXIST armor (
    id INTEGER PRIMARY KEY UNSIGNED NOT NULL AUTO_INCREMENT,
    name TEXT NOT NULL,
    armorValue INTEGER NOT NULL
);

CREATE TABLE IF NOT EXIST consumable (
    id INTEGER PRIMARY KEY UNSIGNED NOT NULL AUTO_INCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXIST questItem (
    id INTEGER PRIMARY KEY UNSIGNED NOT NULL AUTO_INCREMENT,
    name TEXT UNIQUE NOT NULL
);
